// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cadeteria;

#nullable disable

namespace cadeteria.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("cadeteria.Models.Cadetes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cadete", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Entre rios",
                            Nombre = "Jaun Castellanos",
                            Telefono = "231321231"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "independencia",
                            Nombre = "Ana Hume",
                            Telefono = "231321231"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
